# Generated by Django 5.1.7 on 2025-04-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_start_time_bid_create_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
