# Generated by Django 5.1.7 on 2025-04-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_auctionpost_image"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bid",
            constraint=models.UniqueConstraint(
                fields=("auction_post", "user"), name="unique_bid_per_post_user"
            ),
        ),
    ]
