# Generated by Django 5.1.7 on 2025-04-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_bid_unique_bid_per_post_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="telephone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
