# Generated by Django 5.1.7 on 2025-04-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_user_telegram_user_telephone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionpost",
            name="is_active",
        ),
    ]
